theme: jekyll-theme-minimal

lang: zh-CN
title: 金融新闻
show_downloads: false
safe: true
url: https://finews.withounder.com
enforce_ssl: finews.withounder.com
timezone: Asia/Shanghai
author: ZNing

google_analytics: G-MTYH758FNF
