name: 'get_emnews'

on:
  push:
    branches:
      - main
  schedule:
    - cron: '1,6,11,16,21,26,31,36,41,46,51,56 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout from repo
      uses: actions/checkout@main
      with:
        ref: main

    - name: Install Python latest
      uses: actions/setup-python@main
      with:
        python-version: '3.x'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Doing fetch and convert
      run: python get_emnews.py

    - name: Doing fetch and convert 2
      run: python get_emnews_2.py
      
    - name: Commit files
      run: |
        git config --local user.email "zhn038@gmail.com"
        git config --local user.name "ZNing"
        git add .
        git commit -m "提交更新 $(date "+%Y-%m-%d %H:%M:%S")"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
